### ISSUE TITLE
Underwater environment is too blue and foggy

### ISSUE THREAD

**Issue by sergiiiproductengine** [secondlife/viewer#2788] opened 2024-10-04 07:12 UTC
**Steps to reproduce:**
1. Download [7.1.11.11074622243 viewer](https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2364c055f-ExtraFPS) and login.
2. Teleport to the http://maps.secondlife.com/secondlife/Bug%20Island%202/128/127/12 facing Southeast.
3. Change Render Settings to High-Ultra, Mid, Low-Mid or Low.
4. Observe environment.

**Actual result:** 
Underwater environment is too blue and foggy.

<details><summary>OSX actual screenshots</summary>
<p>

High - Ultra
<img width="1579" alt="osx high-ultra" src="https://github.com/user-attachments/assets/0e4a245a-621c-4976-add2-815a95d75548">

Mid
<img width="1579" alt="osx mid" src="https://github.com/user-attachments/assets/890f8261-52fb-4d03-9656-c05657d90c44">

Low - Mid
<img width="1576" alt="osx low-mid" src="https://github.com/user-attachments/assets/41a282df-fa52-4b2a-a3ca-45242a069d0c">

Low
<img width="1580" alt="osx low" src="https://github.com/user-attachments/assets/6ad1c706-bf76-4dd9-b536-b66eaf1791d1">

</p>
</details> 

<details><summary>Win11 actual screenshots</summary>
<p>

High - Ultra
![win11 high-ultra](https://github.com/user-attachments/assets/c5d8563f-c291-4c54-8489-0cf84c9b7545)

Mid
![win11 mid](https://github.com/user-attachments/assets/68b9f2e2-650c-49b9-b496-40f6b2bd7b05)

Low - Mid
![win11 low-mid](https://github.com/user-attachments/assets/342a0739-e112-46f1-9b96-420e92efec6d)

Low
![win11 low](https://github.com/user-attachments/assets/b7ee4fbe-346a-4ea1-a03a-e69bf870a936)

</p>
</details>

**Expected result:**
Underwater environment should not be so blue and foggy.
The far away terrain should be slightly blue and foggy.

<details><summary>Expected screenshots</summary>
<p>

High - Ultra
![Underwater2_High-Ultra](https://github.com/user-attachments/assets/7e7d29ba-d404-4f73-89c4-c2fd2b058091)

Mid
![Underwater2_Mid](https://github.com/user-attachments/assets/625476e3-0b5f-46f8-8888-110a156f4e14)

Low - Mid
![Undewater2_Low-Mid](https://github.com/user-attachments/assets/f32b8e4c-9eea-47f3-9134-f78a3e986ab6)

Low
![Undewater2_Low](https://github.com/user-attachments/assets/a98e51b3-20c4-4119-a43f-17f237a489f0)

</p>
</details> 

**According to** the [Environment Rendering conformity](https://lindenlab.atlassian.net/wiki/spaces/QA/pages/748323232/Environment+Rendering+conformity+test) test plan.
Underwater Rendering - Test 1, 2, 3, 4 - 2) The far away terrain is slightly blue and foggy.

**Additional info:**
The issue is reproduced on Win10/Win11/OSX.
The issue is not reproduced on the current release viewer (Second Life Release 7.1.10.10800445603).
Note: blue and foggy environment with terrain almost invisible on the current release viewer and differs from expected screenshots provided in the test plan (please, compare actual screenshot below with expected screenshots above).

<details><summary>Actual release 7.1.10.10800445603 screenshots</summary>
<p>

OSX:
<img width="1467" alt="release" src="https://github.com/user-attachments/assets/201e343e-9f02-4e41-8f1b-48dbe73219fc">

Win10:
![win10 release](https://github.com/user-attachments/assets/d23cdd19-22ae-4a96-ae31-7fc15c93e7dc)

</p>
</details> 

<details><summary>OSX Environment</summary>
<p>

Second Life Release 7.1.11.11074622243 (64bit)
Release Notes

You are at 128.5, 125.6, 11.8 in Bug Island 2 located at simhost-0ad04c4bcce5e167c.agni
SLURL: http://maps.secondlife.com/secondlife/Bug%20Island%202/128/126/12
(global coordinates 260480.0, 249470.0, 11.8)
Second Life Server 2024-09-13.10853867644
Release Notes

CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (2200 MHz)
Memory: 16384 MB
OS Version: macOS 12.6.0 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon Pro 555X OpenGL Engine

OpenGL Version: 4.1 ATI-4.8.101

Window size: 1472x920
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 64m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 0
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (0.0% used)
HiDPI display mode: 

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091638
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/640 (0.0%)
October 04 2024 00:04:27

</p>
</details>

**Comment by Dan-Linden** [comment] 2024-11-08 17:47
This may have been fixed by a patch for loading EEP settings. Please test again.

**Comment by igorlproductengine** [comment] 2024-11-11 13:13
Failed QA.
Verified on the Second Life Release 7.1.11.11750364439 (64bit) in the scope of https://github.com/secondlife/iqa/issues/381 on Win10/OSX.

There is currently no strong underwater shading as seen previously. Shadows are rendered incorrectly and unattractively. Water transparency is inconsistent; it does not match the expected transparency, and at default settings below High the water appears completely opaque, not as seen in previous versions.

Actual: 
![Image](https://github.com/user-attachments/assets/aed9dc43-e737-4f11-87c1-aa3a811452bd)

**Comment by akleshchev** [comment] 2024-11-20 19:08
To me it looks identical.

7.1.10 (deltaFPS)
![Image](https://github.com/user-attachments/assets/3eb260aa-bf9a-4d16-857b-ab88176691fe)

7.1.11 (extraFPS)
![Image](https://github.com/user-attachments/assets/6b191f27-d1dc-4b3f-8691-183d8b81fdb6)

**Comment by valeriiaaproductengine** [comment] 2024-11-25 10:06
Failed QA.

In Second Life Release 7.1.11.11982653819 build, the water and environment are not the same as in the test plan. When the graphics are set to Mid, the water looks darker than in the screenshots in the test plan. Also, everything becomes very light underwater when the graphics are set to High+. See the screenshots below:

actual_Win10_11982653819_Mid.png:

![Image](https://github.com/user-attachments/assets/0f3c94bf-577c-4fc2-a557-120d7bfeee15)

expected_from_testplan_Mid.png:

![Image](https://github.com/user-attachments/assets/945952c2-e5d9-4031-a371-acb86b453443)

actual_Win10_11982653819_High_plus.png:

![Image](https://github.com/user-attachments/assets/893ed6f7-19d3-40c5-aa1f-3bf7ba0cce08)

expected_from_testplan_High_plus.png:

![Image](https://github.com/user-attachments/assets/ed416523-3c8f-4f65-a83d-f6b5d79eb8ae)


Verified on the Second Life Release 7.1.11.11982653819 (64bit) in the scope of https://github.com/secondlife/iqa/issues/395 on Win10/OSX.

**Comment by AtlasLinden** [comment] 2024-11-25 15:57
The behaviour outlined in the above comment is due to a change to the feature table in PBR viewers (7.x+). That is, the Transparent Water setting is now enabled at different graphics quality settings. A much needed update is required for the aforementioned test plan to verify these changes. 

As for the initial bug report, environment underwater is too blue and foggy, this is no longer reproducing and appears to match the behaviour seen in DeltaFPS.
Passing QA.

**Closed** 2024-12-18 19:48 UTC
Labels: bug, add_to_regression_test
