### ISSUE TITLE
The Fresnel Scale slider can be dragged to values ranging from 0.00 - 1.00

### ISSUE THREAD

**Issue by vladyslavasproductengine** [secondlife/viewer#2359] opened 2024-08-20 09:49 UTC
### Environment

Second Life Test 7.1.9.10164740217 (64bit)
Release Notes

You are at 115.6, 233.4, 19.2 in Product Engine 2 located at simhost-02ddae96b0613bb32.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine%202/116/233/19
(global coordinates 337,012.0, 307,433.0, 19.2)
Second Life Server 2024-06-11.9458617693
Release Notes

CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (2712 MHz)
Memory: 8067 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4780)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: GeForce 940MX/PCIe/SSE2

Windows Graphics Driver Version: 25.21.14.1735
OpenGL Version: 4.6.0 NVIDIA 417.35

Window size: 1920x1001
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 96m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 1
Texture memory: 2048MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 46/31,234 (0.1%)
August 20 2024 02:32:25

### Description

see Reproduction steps

### Reproduction steps

Reproduction steps

1. Install, open the viewer and log in.
2. Open a new Water setting
3. The Fresnel Scale slider try to dragged to values ranging from 0.00 - 20.00

Actual result:
The Fresnel Scale slider can be dragged to values ranging from 0.00 - 1.00.

Expected result:
The Fresnel Scale slider should change to values ranging from 0.00 - 20.00.

Note:
This issue was found acording to the test plan: 3.1.4 Fresnel Scale
https://lindenlab.atlassian.net/wiki/spaces/QA/pages/3053551633/EEP+Environment+Enhancement+Project+Test+Plan
This issue is reproduced on the current production build Second Life Release 7.1.8.9375512768 (64bit).
This issue is reproduced Win10/OSX.
see screnshots:
![еуые12345678](https://github.com/user-attachments/assets/1f5d0cb6-2586-468e-876a-5c97782125aa)

**Comment by akleshchev** [comment] 2024-08-20 10:35
Looks like expected behavior to me, shader does this:
```
   // incoming scale is [0, 1] with 0.5 being default
    // shift to 0.5 to 1.5
    f *= (fresnelScale - 0.5)+1.0;
```
I can make viewer translate that 0..1 range to 0..20, but better option might be to update QA's docks. Clarifying in slack.

**Comment by AtlasLinden** [comment] 2024-08-20 13:35
Yes the test plan just needs to be updated. Closing this as expected behaviour.

**Closed** 2024-08-20 15:27 UTC
Labels: bug, triage
