### ISSUE TITLE
Failure when uploading map Occlusion [R] / Roughness [G] / Metalness [B] does not upload RED channel

### ISSUE THREAD

**Issue by JoseCarlos-Balan** [secondlife/viewer#1311] opened 2024-04-24 09:16 UTC
### Environment

from this version Second Life Release 7.1.6.8757451456

### Description

Failure when uploading map Occlusion [R] / Roughness [G] / Metalness [B] does not upload RED channel, upload the texture but ignore the RED channel which refers to the occlusion, I attach a photo, the large image is the real texture
![Captura de pantalla 2024-04-24 110215](https://github.com/secondlife/viewer/assets/55196362/ad51f084-9a4c-44c7-98f8-102e5ae2a908)

### Reproduction steps

uploading map Occlusion [R] / Roughness [G] / Metalness [B]

**Comment by wild-run** [comment] 2024-04-25 15:07
Version Second Life Release 7.1.6.8727446379 (64bit) work ok for map Occlusion [R] / Roughness [G] / Metalness [B] and it also uploads them in 2k, but apart from this version something is wrong and it does not upload the red channel (occlusion)

**Comment by kylelinden** [comment] 2024-04-25 16:13
QA to repro

**Comment by RunitaiLinden** [comment] 2024-05-03 14:25
Dupe of #1382

**Comment by Dan-Linden** [comment] 2024-06-07 13:50
Closed as duplicate.

**Closed by Dan-Linden** 2024-06-07 13:50 UTC
Labels: bug, triage
