### ISSUE TITLE
Watchdog crash is not appeared in the Bugsplat

### ISSUE THREAD

**Issue by vladyslavasproductengine** [secondlife/viewer#1839] opened 2024-06-25 10:28 UTC
### Environment

Second Life Release 7.1.9.9620320242 (64bit)
Release Notes

CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (2200 MHz)
Memory: 16384 MB
OS Version: macOS 12.7.3 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Sun Dec 17 22:55:27 PST 2023; root:xnu-8020.240.18.706.2~1/RELEASE_X86_64 x86_64
Graphics Card Vendor: Intel Inc.
Graphics Card: Intel Iris Pro OpenGL Engine

OpenGL Version: 4.1 INTEL-18.8.6

Window size: 1440x776
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 64m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 0
Texture memory: 1536MB
Disk cache: Max size 1638.4 MB (1.8% used)
HiDPI display mode: 

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version:  

June 25 2024 02:20:31

### Description

see reproduction steps

### Reproduction steps

Steps to reproduce:

1. Log into Viewer with the following command line argument: --set WatchdogEnabled 1
2. Open your Developer menu (Ctrl-Alt-Q) and click Develop > Force An Error > Infinite Loop, and start your stopwatch
3. Open the "Bugsplat" 

Actual result:
Watchdog crash is not appeared in the Bugsplat.

Expected result:
Watchdog crash should appear in the Bugsplat.

Additional information:
The issue is reproduced on the OSX and Win10.
The issue was found according to the test plan:2.4.1 If Watchdog should be ON:https://docs.google.com/document/d/1tgyjorCYIjaNCUNBTsOn8WDX-eLQTIx6Tds1GQQ-7H4/edit?pli=1#heading=h.k8x305-fwa0lo

Bugsplat:https://app.bugsplat.com/v2/crashes?c0=appVersion&f0=CONTAINS&v0=7.1.9.9620320242&database=SecondLife_Viewer_2018

**Comment by RunitaiLinden** [comment] 2024-07-09 22:31
Same root cause as #1826, fixed with https://github.com/secondlife/viewer/pull/1966

**Comment by akleshchev** [comment] 2024-07-10 09:58
https://github.com/secondlife/viewer/issues/1826 got a fix that is likely to affect this, please retest.

**Comment by vladyslavasproductengine** [comment] 2024-07-16 10:58
Fail QA.
Verified on the Second Life Release 7.1.9.9865199239 (64bit) on Win10/OS X in the scope of https://github.com/secondlife/iqa/issues/282 .

Crashes are appeared but displays are not correctly and different on Win 10 and Mac.

Bugsplat: https://app.bugsplat.com/v2/crashes?c0=appVersion&f0=CONTAINS&v0=7.1.9.9865199239&database=SecondLife_Viewer_2018
Win10: https://app.bugsplat.com/v2/crash?database=SecondLife_Viewer_2018&id=1494887
Mac: https://app.bugsplat.com/v2/crash?database=SecondLife_Viewer_2018&id=1494892

see screenshots:
![cr4](https://github.com/user-attachments/assets/263dcd0a-10fd-421d-9e46-7dd458aac5c1)
![cr5](https://github.com/user-attachments/assets/430795d2-b347-417c-84c9-2dc0ed37f1a5)
![cr6](https://github.com/user-attachments/assets/ae8a747a-d129-4ecd-96c3-bbffee60c9c0)

**Comment by AtlasLinden** [comment] 2024-07-16 21:10
Watchdog crashes are now being reported so passing QA for this issue.
Issue regarding the different Bugsplat reports has been made [here](https://github.com/secondlife/viewer/issues/2043).

**Closed** 2024-08-26 17:24 UTC
Labels: bug
