### ISSUE TITLE
Mirror preferences should update when Graphics Quality is adjusted.

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#1472] opened 2024-05-14 20:46 UTC
### Environment

Second Life Release 7.1.7.9020640347 (64bit)
Release Notes

You are at 121.3, 88.1, 21.8 in By Design located at simhost-0ed1af4f6c09b0a7a.agni
SLURL: http://maps.secondlife.com/secondlife/By%20Design/121/88/22
(global coordinates 261,497.0, 246,872.0, 21.8)
Second Life Preflight 2024-04-13.8669470296
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4291)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.3623
OpenGL Version: 4.6.0 NVIDIA 536.23

Window size: 3840x2066
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 64m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 0
Texture memory: 7304MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.399bd0e

Packets Lost: 5/34,240 (0.0%)
May 14 2024 13:32:33

### Description

Advanced Graphics Preferences > “Mirror Resolution” and “Mirror Update Rate” should change when adjusting the Graphics Quality slider.
They should also update when clicking “Reset to Recommended Settings”

![image](https://github.com/secondlife/viewer/assets/119471733/87f09216-7b5c-45a8-8a6b-7e6e420bcc05)

### Reproduction steps

1. Open Preferences > Graphics and click Advanced Settings... button.
2. Slide the Quality & speed slider in the Preferences floater right and left.
3. Verify “Mirror Resolution” and “Mirror Update Rate” update to correct values for each Quality setting
4. Low: Mirror Resolution= ___ , Mirror Update Rate= ___
5. Low+: Mirror Resolution= ___ , Mirror Update Rate= ___
6. Mid: Mirror Resolution= ___ , Mirror Update Rate= ___
7. Mid+: Mirror Resolution= ___ , Mirror Update Rate= ___
8. High: Mirror Resolution= ___ , Mirror Update Rate= ___
9. High+: Mirror Resolution= ___ , Mirror Update Rate= ___
10. Ultra: Mirror Resolution= ___ , Mirror Update Rate= ___
11. Click the Reset to Recommended Settings button and verify the Mirror Resolution and Mirror Update Rate match the settings for that Quality Level.

Observed: The “Mirror Resolution” and “Mirror Update Rate” settings do not change when moving the Quality slider or clicking the Reset to Recommended Settings button.

**Comment by brad-linden** [comment] 2024-09-25 23:57
this is not reproing for me.  I think it may have gotten fixed by other featuretable cleanup work

**Comment by DmitrySProductengine** [comment] 2024-09-30 08:54
Failed QA.
Verified on the Second Life Release 7.1.11.11074622243 (64bit) on Win11/OSX in the scope of [IQA #356](https://github.com/secondlife/iqa/issues/356).

In general, when changing graphic settings, the mirror preferences change, but there is a problem with the Low mode.
When selecting the Low mode, the preference ‘Mirror Update Rate’ does not change (the value from the previous mode remains).
Perhaps when selecting the Low mode, this preference should also switch to the Low value.
This issue is reproduced on Win11 and OSX.
This issue is reproduced on the current release 7.1.10.10800445603 build.

Also, there is a slight difference in the resolution of mirrors for Windows and Mac (in High/Ultra and Ultra modes), but perhaps it depends on the power of the computer and looks acceptable:
Mac (CPU: Intel(R) Core(TM) i7-9750H CPU; Memory: 16384 MB; Graphics Card: AMD Radeon Pro 555X OpenGL Engine):
Low:                                                             Mirror Resolution: 256  ;                              Mirror Update Rate: Medium
Low/Mid:                                                      Mirror Resolution: 256   ;                             Mirror Update Rate: Medium
Mid:                                                              Mirror Resolution: 512    ;                             Mirror Update Rate: Medium
Mid/High:                                                     Mirror Resolution: 512     ;                            Mirror Update Rate: High
High:                                                             Mirror Resolution: 512     ;                            Mirror Update Rate: High
High/Ultra:                                                    Mirror Resolution: 512      ;                          Mirror Update Rate: Ultra
Ultra:                                                             Mirror Resolution: 1024     ;                         Mirror Update Rate: Ultra
Reset to recommended settings: Mid:       Mirror Resolution: 512        ;                       Mirror Update Rate: Medium

Win11 (CPU: AMD Ryzen 7 5800H; Memory: 14189 MB; Graphics Card: NVIDIA GeForce RTX 3070 Laptop):
Low:                                                                 Mirror Resolution: 256   ;                              Mirror Update Rate: Medium
Low/Mid:                                                          Mirror Resolution: 256    ;                             Mirror Update Rate: Medium
Mid:                                                                  Mirror Resolution: 512     ;                             Mirror Update Rate: Medium
Mid/High:                                                         Mirror Resolution: 512      ;                            Mirror Update Rate: High
High:                                                                 Mirror Resolution: 512      ;                           Mirror Update Rate: High
High/Ultra:                                                       Mirror Resolution: 1024     ;                          Mirror Update Rate: Ultra
Ultra:                                                                Mirror Resolution: 2048     ;                         Mirror Update Rate: Ultra
Reset to recommended settings: High:        Mirror Resolution: 512         ;                        Mirror Update Rate: High

See the attached video:
1. Actual

**Comment by akleshchev** [comment] 2024-10-15 18:47
> Also, there is a slight difference in the resolution of mirrors for Windows and Mac

These platforms have intentionally different feature tables. Since mac's gpu are generally weaker, it's within the norm to have lower parameters.

**Comment by DmitrySProductengine** [comment] 2024-10-24 10:00
Passed QA.
Verified on the Second Life Release 7.1.11.11469579464 (64bit) on Win11/OSX in the scope of [IQA #374](https://github.com/secondlife/iqa/issues/374).

Current settings values:
Mac (CPU: Intel(R) Core(TM) i7-9750H CPU; Memory: 16384 MB; Graphics Card: AMD Radeon Pro 555X OpenGL Engine): 
Low: Mirror Resolution: 256 ; Mirror Update Rate: Low 
Low/Mid: Mirror Resolution: 256 ; Mirror Update Rate: Medium 
Mid: Mirror Resolution: 512 ; Mirror Update Rate: Medium 
Mid/High: Mirror Resolution: 512 ; Mirror Update Rate: High 
High: Mirror Resolution: 512 ; Mirror Update Rate: High 
High/Ultra: Mirror Resolution: 512 ; Mirror Update Rate: Ultra 
Ultra: Mirror Resolution: 1024 ; Mirror Update Rate: Ultra 
Reset to recommended settings: Mid: Mirror Resolution: 512 ; Mirror Update Rate: Medium

Win11 (CPU: AMD Ryzen 7 5800H; Memory: 14189 MB; Graphics Card: NVIDIA GeForce RTX 3070 Laptop): 
Low: Mirror Resolution: 256 ; Mirror Update Rate: Low 
Low/Mid: Mirror Resolution: 256 ; Mirror Update Rate: Medium 
Mid: Mirror Resolution: 512 ; Mirror Update Rate: Medium 
Mid/High: Mirror Resolution: 512 ; Mirror Update Rate: High 
High: Mirror Resolution: 512 ; Mirror Update Rate: High 
High/Ultra: Mirror Resolution: 1024 ; Mirror Update Rate: Ultra 
Ultra: Mirror Resolution: 2048 ; Mirror Update Rate: Ultra 
Reset to recommended settings: High: Mirror Resolution: 512 ; Mirror Update Rate: High

**Comment by Dan-Linden** [comment] 2024-10-24 17:55
This test needs to be added to our Preferences viewer Regression test.

**Closed** 2024-12-18 19:47 UTC
Labels: bug, team:viewer, testplan_todo, add_to_regression_test
