### ISSUE TITLE
[OSX]The draw distance does not change on OSX after selecting the ‘Adjust continuously’ checkbox.

### ISSUE THREAD

**Issue by vladyslavasproductengine** [secondlife/viewer#2292] opened 2024-08-14 13:18 UTC
### Environment

Second Life Test 7.1.9.10164740217 (64bit)
Release Notes

You are at 125.1, 130.0, 22.5 in Product Engine 2 located at simhost-02ddae96b0613bb32.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine%202/125/130/23
(global coordinates 337021.0, 307330.0, 22.5)
Second Life Server 2024-06-11.9458617693
Release Notes

CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (2200 MHz)
Memory: 16384 MB
OS Version: macOS 12.7.3 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Sun Dec 17 22:55:27 PST 2023; root:xnu-8020.240.18.706.2~1/RELEASE_X86_64 x86_64
Graphics Card Vendor: Intel Inc.
Graphics Card: Intel Iris Pro OpenGL Engine

OpenGL Version: 4.1 INTEL-18.8.6

Window size: 1440x776
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 32m
Bandwidth: 3000kbit/s
LOD factor: 1.125
Render quality: 1
Texture memory: 1536MB
Disk cache: Max size 1638.4 MB (2.0% used)
HiDPI display mode: 

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/1620 (0.0%)
August 14 2024 06:14:08

### Description

see Reproduction steps

### Reproduction steps

Reproduction steps

1. Install, open the viewer and log in.
2. Open Word->Improve graphics speed->Auto adjust settings
3. Select ‘Reset to recommended settings’
4. Open Preferences>Graphics and observe the default ‘Draw distance’ value. Let’s call this value X.
5. In ‘Auto-adjust settings', change the 'Maximum distance’ to the default draw distance value X (as observed in 
7. Preferences>Graphics).
8. In Preferences>Graphics, drag the 'Draw distance' setting down to the minimum of 64m.
9. Select OK and reopen Preferences>Graphics
10. In ‘Auto-adjust settings', select the ‘Adjust continuously’ checkbox.

Actual result:
The draw distance does not change on OSX after selecting the ‘Adjust continuously’ checkbox.

Expected result:
The draw distance should begin to increase up unto the ‘Maximum distance’ value X.

Note:
This issue was found acording to the test plan: 3.4.2 Maximum Distance
https://lindenlab.atlassian.net/wiki/spaces/QA/pages/2953248839/Improve+Graphics+Speed+Floater+Test+Plan
This issue is reproduced on the current production build Second Life Release 7.1.8.9375512768 (64bit).
This issue is not reproduced Win10.
see screnshots:
<img width="1382" alt="Screenshot 2024-08-14 at 16 13 57" src="https://github.com/user-attachments/assets/77569e2f-311b-4185-924f-cc853f8c8a75">

**Comment by AtlasLinden** [comment] 2024-08-14 20:23
I'm unable to reproduce this issue.
This is likely due to the FPS already being lower than the desired frame rate. 
@vladyslavasproductengine are you able to reproduce this when the FPS is higher than 15? (May require going to an empty region and making the SL viewer window smaller etc.)

The test plan may require being updated to ensure to test this when the FPS is higher than the default 15 or to set the Desired frame rate to a lower value.

**Comment by vladyslavasproductengine** [comment] 2024-08-15 12:18
Hello @AtlasLinden !
This issue is not reproduced if FPS >15.

**Comment by AtlasLinden** [comment] 2024-08-15 13:55
Thanks for checking! In that case the test plan will be updated accordingly and this issue will be closed as expected behaviour.

**Closed by AtlasLinden** 2024-08-15 13:55 UTC
Labels: bug, triage
