### ISSUE TITLE
[Win10] An avatar's shape looks corrupted in-world and in the "Avatar Shape" floater, and after opening the "Avatar Shape" floater, editing and discarding the shape changes

### ISSUE THREAD

**Issue by dmytrohproductengine** [secondlife/viewer#2647] opened 2024-09-23 12:14 UTC
### Environment

Second Life Release 7.1.11.10947335521 (64bit)
Release Notes

You are at 212.6, 105.7, 21.5 in Product Engine located at simhost-07e989f3f263c4188.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/213/106/22
(global coordinates 336,853.0, 307,306.0, 21.5)
Second Life Server 2024-07-22.10048683488
Release Notes

CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (3696 MHz)
Memory: 32688 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4894)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: Radeon RX 5500 XT

Windows Graphics Driver Version: 26.20.15029.27017
OpenGL Version: 4.6.13587 Core Profile Context 20.4.2 26.20.15029.27017

Window size: 1920x1017
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (0.4% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 23/4,223 (0.5%)
September 23 2024 05:13:12

### Description

An avatar's shape looks corrupted in-world and in the "Avatar Shape" floater, and after opening the "Avatar Shape" floater, editing and discarding the shape changes

### Reproduction steps

1. Download and install the [Second Life Release 7.1.11.10947335521](https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23b589d39-ExtraFPS) build.
2. Log in.
3. Mouse right-click on an avatar→"Shape...".
4. Pay attention to the "Avatar Shape" floater preview pictures and the avatar's in-world look.
5. Change any option (e.g. "Height").
6. Close the "Avatar Shape" floater.
7. Click the "Discard" button.
8. Observe the avatar's in-world looking.

**Actual result:**
An avatar's shape looks corrupted in-world and in the "Avatar Shape" floater, and after opening the "Avatar Shape" floater, editing and discarding the shape changes.

**Expected result:**
An avatar's shape should look as expected in-world and in the "Avatar Shape" floater.

**Note:**
This issue is reproduced on Win10 only.
This issue is **not** reproduced on Win11/OSX.

This issue was found during ad-hoc testing of [secondlife/viewer/issues/1997](https://github.com/secondlife/viewer/issues/1997).

**Also**, after saving the current shape or relogin to the viewer, an avatar's shape looks as expected.

This issue is **not reproduced** on the current production build Second Life Release 7.1.10.10800445603.

**actual.mp4**
https://github.com/user-attachments/assets/293ca800-ffd2-45a9-bff0-7be802698f64

**actual.png**
![actual](https://github.com/user-attachments/assets/e0b19bb2-a6d9-42cd-afd1-da9e0bf87fb9)

**expected_release_7.1.10.10800445603.png**
![expected_release_7 1 10 10800445603](https://github.com/user-attachments/assets/650a1b0d-fd62-44ff-871b-c925bb4a4582)

**Comment by AtlasLinden** [comment] 2024-09-25 18:00
Hi @dmytrohproductengine, 
Are you able to update to the latest graphic driver version and see if this issue still reproduces for you?

**Comment by dmytrohproductengine** [comment] 2024-09-26 12:39
Hi, @AtlasLinden.
You were right.
I have updated the GPU driver to the latest version and the issue is not reproduced anymore (see "32.0.11037.4004.png").

Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: Radeon RX 5500 XT
Windows Graphics Driver Version: 32.0.11037.4004

Thank you for the clarification and help!

<details><summary>Environment</summary>
<p>
Second Life Release 7.1.11.10947335521 (64bit)
Release Notes

You are at 213.0, 108.0, 21.5 in Product Engine located at simhost-04fc9fd708f788a32.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/213/108/22
(global coordinates 336,853.0, 307,308.0, 21.5)
Second Life Server 2024-07-22.10048683488
Release Notes

CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (3696 MHz)
Memory: 32688 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4894)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: Radeon RX 5500 XT

Windows Graphics Driver Version: 32.0.11037.4004
OpenGL Version: 4.6.0 Compatibility Profile Context 24.8.1.240822

Window size: 1920x1017
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 4055MB
Disk cache: Max size 1638.4 MB (0.1% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 1/3,987 (0.0%)
September 26 2024 05:31:05
</p>
</details> 

**32.0.11037.4004.png**
![32 0 11037 4004](https://github.com/user-attachments/assets/bfaf4684-762b-4aa2-acdb-9d43b1d7c6c1)

**Comment by kylelinden** [comment] 2024-09-26 18:52
Quattro pulled an ad hoc query on driver usage of 20.4.2 26.20.15029.27017 and found only 123 total residents on those 4 year old drivers since Sep. 1st. Closing this issue and informing support. Work around is to update your drivers. Will float idea of an MotD reminder too.

**Closed by kylelinden** 2024-09-26 18:52 UTC
Labels: bug, triage
