### ISSUE TITLE
Underwater mirror only displays objects and users that touch the surface of the water

### ISSUE THREAD

**Issue by AtlasLinden** [secondlife/viewer#1165] opened 2024-04-09 16:35 UTC
From triage created by [DmitrySProductengine](https://github.com/DmitrySProductengine): secondlife/triage#154  

### Reproduction steps

1. Download and install the Second Life Release 7.1.5.8472515256 viewer (https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23617436b-pmfp).
2. Log in to the Viewer on Aditi and teleport to any region running "PMFP Phase1 2024-03-27.8445048753" (secondlife://Aditi/secondlife/Rumpus+Room+3/74/196/1).
3. Create a mirror as indicated in the Featurettes Test Plan ([2.1 Verify a mirror can be created.](https://lindenlab.atlassian.net/wiki/spaces/QA/pages/3054436428/Featurettes+Test+Plan#2.1-Verify-a-mirror-can-be-created.)).
4. Place the mirror underwater and observe the reflection in the mirror.

**Actual result:**
Underwater mirror only displays objects and users that touch the surface of the water.

**Expected result:** 
The underwater mirror should display all objects and users, regardless of their "depth".

**Additional information:** 
According to the ‘Featurettes Test Plan’ - 2.8 Mirrors test cases - 3. Verify mirrors work under water. (https://lindenlab.atlassian.net/wiki/spaces/QA/pages/3054436428/Featurettes+Test+Plan#2.8-Mirrors-test-cases)
This issue is reproduced on Win10 and OSX.

If an object or user sinks to a great depth (stops touching the surface of the water), it disappears from the reflection of the mirror underwater.
The test plan does not indicate the exact behavior of the mirrors underwater. And perhaps this behavior may be expected and correct.

This issue is not reproduced on the current production release (7.1.4.8149792635) - this feature has not been implemented yet.

See attached screenshots and video:
1. Expected - objects touch the surface of the water.png
<img width="1680" alt="Expected - objects touch the surface of the water" src="https://github.com/secondlife/triage/assets/136308794/943cf0fe-bd46-4bb0-86fa-c4afb308b867">

2. Actual - the object is below the surface of the water.png
<img width="1680" alt="Actual - the object is below the surface of the water" src="https://github.com/secondlife/triage/assets/136308794/46d58d62-5ecd-4de3-9ea0-3cced3319f56">

3. Actual.mp4 
https://github.com/secondlife/triage/assets/136308794/60b5d235-47ad-4e47-8d52-918841fdb627

<details><summary>Environment:</summary>
<p>

Second Life Release 7.1.5.8472515256 (64bit)
Release Notes

You are at 74.1, 195.8, 1.0 in Rumpus Room 3 located at simhost-0fb30e2027b062e1d.aditi
SLURL: secondlife://Aditi/secondlife/Rumpus+Room+3/74/196/1
(global coordinates 35658.1, 12739.8, 1.0)
PMFP Phase1 2024-03-27.8445048753
Release Notes

CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (2600 MHz)
Memory: 16384 MB
OS Version: Mac OS X 13.6.4 Darwin 22.6.0 Darwin Kernel Version 22.6.0: Sun Dec 17 22:18:09 PST 2023; root:xnu-8796.141.3.703.2~2/RELEASE_X86_64 x86_64
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon Pro 555X OpenGL Engine

OpenGL Version: 4.1 ATI-4.14.1

Window size: 1078x866
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.25
Render quality: 2
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (100.1% used)
HiDPI display mode: 0

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.13
Dullahan: 1.14.0.202310131309
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.399bd0e

Packets Lost: 0/7049 (0.0%)
April 02 2024 01:42:06

</p>
</details>

**Comment by Geenz** [comment] 2024-05-08 19:09
I'm unable to reproduce this.
![image](https://github.com/secondlife/viewer/assets/341813/065ffa55-dc98-469b-886d-63661a8436c0)
![image](https://github.com/secondlife/viewer/assets/341813/731eb01e-c1de-4542-9486-4ab487ae918c)

**Comment by Geenz** [comment] 2024-05-08 19:48
Found a good repro.  Pushed a fix.  Should hopefully be in the next build.

**Closed** 2024-06-10 20:26 UTC
Labels: bug
