### ISSUE TITLE
[ExtraFPS] Scale of animated textures is changing

### ISSUE THREAD

**Issue by Dan-Linden** [secondlife/viewer#2848] opened 2024-10-14 19:03 UTC
### Environment

Second Life Release 7.1.11.11074622243 (64bit)
Release Notes

You are at 140.9, 225.5, 133.7 in Linden Lab HQ 4 located at simhost-0ed1af4f6c09b0a7a.agni
SLURL: http://maps.secondlife.com/secondlife/Linden%20Lab%20HQ%204/141/226/134
(global coordinates 238,989.0, 244,194.0, 133.7)
Second Life Preflight 2024-09-30.11111372425
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.91 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4894)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.6590
OpenGL Version: 4.6.0 NVIDIA 565.90

Window size: 1712x1217
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.75
Render quality: 5
Texture memory: 8192MB
Disk cache: Max size 1638.4 MB (100.0% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Secondlife WebRTC Gateway 

Packets Lost: 0/2,157 (0.0%)
October 14 2024 11:56:49

### Description

The scale of animated textures changes in the 7.1.11.11074622243 - ExtraFPS viewer
This does not reproduce in the 7.1.10.10800445603 - DeltaFPS viewer.

### Reproduction steps

1. Go to http://maps.secondlife.com/secondlife/Linden%20Lab%20HQ%204/141/226/134
2. Make the Second Life window relatively small (I used 1512 x 1257)
3. Watch the animated leaves on the tree.
Observed: The texture of the leaves occasionally grows larger and smaller.

Expected: The texture of the leaves should appear to move, but not change scale.

Repro 2
1. Alt-zoom on the animated textures at http://maps.secondlife.com/secondlife/Bug%20Island/49/9/27

Observed: Sometimes the numbers on the textures stop moving or disappear.
Video: https://github.com/user-attachments/assets/cbfbaea0-fee2-4928-b41d-9bb7c03ac890

Expected: The textures never stop moving.

**Comment by Dan-Linden** [comment] 2024-10-30 16:44
From what I can see this is fixed in ExtraFPS 7.1.11.11565212741.

**Comment by Dan-Linden** [comment] 2024-11-01 22:09
Let's send this to QA and see if it's fixed for them.

**Comment by georgebproductengine** [comment] 2024-11-11 14:30
Passed QA.
Verified on the Second Life Release 7.1.11.11750364439 (64bit) in the scope of https://github.com/secondlife/iqa/issues/381 on Win10/OSX.

**Comment by cosmic-linden** [comment] 2024-11-20 18:04
I might pick this up later, but don't want to block anyone while I'm working on another ticket (https://github.com/secondlife/viewer/issues/3104)

**Comment by Dan-Linden** [comment] 2024-11-20 20:15
Here's video of the leaves changing at http://maps.secondlife.com/secondlife/Linden%20Lab%20HQ%204/141/226/134 on build 7.1.11.11750364439
https://github.com/user-attachments/assets/c95bec2e-6e12-47c3-ae4d-ef4b652794e0
They look fine on 7.1.10.10800445603 for me.

**Comment by Dan-Linden** [comment] 2024-11-21 01:44
The leaves changing bug does not reproduce on my Windows/AMD machine or on my Mac M1.

OS Version: Microsoft Windows 11 64-bit (Build 22631.4460)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon RX 6800M
Windows Graphics Driver Version: 30.0.15020.1001
OpenGL Version: 4.6.14800 Core Profile Context 21.50.20.01 30.0.15020.1001

**Comment by Dan-Linden** [comment] 2024-11-21 20:13
Something in the octree is changing.
Second Life Release 7.1.11.11750364439 (64bit) / Windows 10/ NVIDIA GeForce GTX 1080/PCIe/SSE2
SLURL: http://maps.secondlife.com/secondlife/Linden%20Lab%20HQ%204/141/226/134

https://github.com/user-attachments/assets/2d31ea7f-6c9f-417e-8785-af590f90d948

**Comment by Dan-Linden** [comment] 2024-11-21 21:05
This doesn't repro much for me if my viewer is maximized. Maybe this is framerate related. If I shrink the viewer to a quarter of the screen so the FPS is 60+ then this bug reproduces. 
I've also been able to reproduce this on a Win11 / GeForce GTX 1660 Ti (laptop)

**Comment by Dan-Linden** [comment] 2024-11-21 23:32
After shrinking the viewer window size this bug **does** also reproduce on my Windows/AMD machine and my Mac M1.

OS Version: Microsoft Windows 11 64-bit (Build 22631.4460)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon RX 6800M
Windows Graphics Driver Version: 30.0.15020.1001
OpenGL Version: 4.6.14800 Core Profile Context 21.50.20.01 30.0.15020.1001

**Comment by Dan-Linden** [comment] 2024-11-21 23:36
This issue does not repro in Develop, but this tree has a different issue in Develop, https://github.com/secondlife/viewer/issues/3127.

**Comment by akleshchev** [comment] 2024-11-22 17:42
Ok, should this be moved to Develop?

**Comment by akleshchev** [comment] 2024-11-22 18:00
"scale of aniamted textures" reproes for me if I resize window to be small.

I think fix for scaled textures is https://github.com/secondlife/viewer/commit/a068928c374f7918682d069b284588af464ec43d
Can not repro after applying it

**Comment by cosmic-linden** [comment] 2024-11-23 01:05
@akleshchev I can still reproduce the bug in `release/2024.09-ExtraFPS` with https://github.com/secondlife/viewer/commit/a068928c374f7918682d069b284588af464ec43d applied

**Comment by cosmic-linden** [comment] 2024-11-23 01:36
Looking at `Render Metadata > Texture Anim`, I see that:

- Impacted prims at Bug Island (http://maps.secondlife.com/secondlife/Bug%20Island/49/9/27) are no longer highlighted in yellow when I zoom out/back in
- Impacted prims at the treehouse (http://maps.secondlife.com/secondlife/Linden%20Lab%20HQ%204/141/226/134) remain highlighed in yellow when I wait and they rebuild

This may be two flavors of the bug with the same root cause, or possibly two distinct bugs.

I will try to repro again in develop, with and without @akleshchev 's cherry pick fix.

**Comment by cosmic-linden** [comment] 2024-11-23 02:02
I am unable to reproduce the bug in develop with and without the fix mentioned at https://github.com/secondlife/viewer/commit/a068928c374f7918682d069b284588af464ec43d - it would seem that fix is neither necessary nor sufficient.

**Comment by akleshchev** [comment] 2024-11-23 02:24
Also can repro, but it didn't repro for some time, looks like it periodically stabilizes. Forcing all textures to be FullRes does not affect it, there is no record in texture console, so it probably isn't fetcher.

**Comment by cosmic-linden** [comment] 2024-11-23 02:30
Cherry picking the main fixes from secondlife/viewer#2768 seemed to fix the issues on my end:

https://github.com/secondlife/viewer/pull/3143

**Comment by dmytrohproductengine** [comment] 2024-11-25 10:17
Passed QA.

Verified on the Second Life Release 7.1.11.11982653819 (64bit) on Win10/OSX in the scope of [IQA#395](https://github.com/secondlife/iqa/issues/395).

Verified on http://maps.secondlife.com/secondlife/Bug%20Island/49/9/27 location using the "Alt-zoom" option on the animated textures.

**Also**, the PE Team does not have access to http://maps.secondlife.com/secondlife/Linden%20Lab%20HQ%204/141/226/134 location.
If it is necessary, could you please provide access to that region?
Thanks.

**Comment by Dan-Linden** [comment] 2024-11-25 21:45
I still see this on build 7.1.11.11982653819 at http://maps.secondlife.com/secondlife/Linden%20Lab%20HQ%204/142/226/134

Video: https://github.com/user-attachments/assets/fd825351-30d7-4c1f-85fa-6cb886613ba3

**Comment by akleshchev** [comment] 2024-11-25 22:24
Fix wasn't merged yet.
https://github.com/secondlife/viewer/pull/3143

**Comment by vladyslavasproductengine** [comment] 2024-11-27 13:39
Failed QA.
Verified on the Second Life Release 7.1.11.12041172537 (64bit) on OSX in the scope of secondlife/iqa#401.

Verified on http://maps.secondlife.com/secondlife/Bug%20Island/47/15/27 location using the "Alt-zoom" option on the animated textures.
Win 10: Sometimes the numbers on the textures stop moving        
OSX: The numbers on the textures are blurry see the video:
https://github.com/user-attachments/assets/e65ae169-61e3-477b-91d4-f47c940184f0


Also, the PE Team does not have access to http://maps.secondlife.com/secondlife/Linden%20Lab%20HQ%204/141/226/134 location.
If it is necessary, could you please provide access to that region?
Thanks.

**Comment by AtlasLinden** [comment] 2024-11-27 19:54
The original bug, that is the scale of animated textures, no longer occurs.
Passing QA

The textures blurring or animation stopping are not related to the scale and can be investigated elsewhere.

**Closed** 2024-12-18 19:48 UTC
Labels: bug, team:viewer
