### ISSUE TITLE
Resaving does not save changes to the Day Cycle

### ISSUE THREAD

**Issue by DmitrySProductengine** [secondlife/viewer#2735] opened 2024-09-30 09:59 UTC
### Environment
<details><summary>Environment</summary>
<p>

Second Life Release 7.1.11.11074622243 (64bit)
Release Notes

You are at 121.5, 114.1, 22.9 in Product Engine 3 located at simhost-06c92da1cee01d90f.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine%203/122/114/23
(global coordinates 336762.0, 307058.0, 22.9)
Second Life Server 2024-07-22.10048683488
Release Notes

CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (2600 MHz)
Memory: 16384 MB
OS Version: macOS 14.5.0 Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 x86_64
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: AMD Radeon Pro 555X OpenGL Engine

OpenGL Version: 4.1 ATI-5.5.17

Window size: 996x995
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.25
Render quality: 2
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (0.2% used)
HiDPI display mode: 

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091638
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/386 (0.0%)
September 30 2024 02:57:28

</p>
</details> 

### Reproduction steps

1. Download and install the Second Life Release 7.1.11.11074622243 viewer (https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%2364c055f-ExtraFPS).
2. Log in to the Viewer.
3. Create a new Day Cycle.
4. Change some settings.
5. Click on the ‘Save’ button.
6. Change some settings again.
7. Click on the ‘Save’ button.
8. Close and open this Day Cycle.
 
**Actual result:**
Resaving does not save changes to the Day Cycle.

**Expected result:**
Resaving should save changes to the Day Cycle.

**Additional information:**
This issue was found during ticket verification (https://github.com/secondlife/viewer/issues/2627) in the scope of [IQA #356](https://github.com/secondlife/iqa/issues/356).
This issue is reproduced on Win11 and OSX.
This issue is reproduced with ’Save’ and ‘Save As’ buttons.

This issue is not reproduced on the current Second Life Release 7.1.10.10800445603 build.
This issue is not reproduced with Sky and Water settings.

See attached videos:
1. Resaving Save

https://github.com/user-attachments/assets/088e1427-57e2-4610-b308-492a08ca7010

2. Resaving Save As

https://github.com/user-attachments/assets/d9d6ae0b-7d76-454f-b721-e4352de2a4a7

**Comment by kylelinden** [comment] 2024-09-30 16:40
assigned to @akleshchev to investigate against sky setting changes.

**Comment by sergiiiproductengine** [comment] 2024-10-18 07:45
Passed QA.

Verified on the Second Life Release 7.1.11.11296522354 (64bit) on Win10/OSX in the scope of https://github.com/secondlife/iqa/issues/366.

Notes:
Resaving saves changes as expected.
Verified with ’Save’ and ‘Save As’ buttons.
Also, verified that the issue is not reproduced with Sky and Water settings.

**Closed** 2024-12-18 19:47 UTC
Labels: bug, team:viewer, maint-pe
