### ISSUE TITLE
The "Physics Shape Type" parameter is changed back to the "None" option after choosing the "Prim" or "Convex Hull" option in the "Features" tab of the "Build" floater

### ISSUE THREAD

**Issue by dmytrohproductengine** [secondlife/viewer#2646] opened 2024-09-23 09:21 UTC
### Test plan
- The original repro below.
- please test all combo boxes / dropdowns and scroll bars found in each of the following floaters:
    Gestures
    Build
    Inventory
    Whatever other floaters you may think of! 😸

### Environment

Second Life Release 7.1.11.10947335521 (64bit)
Release Notes

You are at 213.6, 106.8, 21.5 in Product Engine located at simhost-07e989f3f263c4188.agni
SLURL: http://maps.secondlife.com/secondlife/Product%20Engine/214/107/22
(global coordinates 336,854.0, 307,307.0, 21.5)
Second Life Server 2024-07-22.10048683488
Release Notes

CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (3696.01 MHz)
Memory: 32688 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4894)
Graphics Card Vendor: ATI Technologies Inc.
Graphics Card: Radeon RX 5500 XT

Windows Graphics Driver Version: 26.20.15029.27017
OpenGL Version: 4.6.13587 Core Profile Context 20.4.2 26.20.15029.27017

Window size: 1920x1017
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 4096MB
Disk cache: Max size 1638.4 MB (0.4% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.23.1 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/936 (0.0%)
September 23 2024 02:21:33

### Description

The "Physics Shape Type" parameter is changed back to the "None" option after choosing the "Prim" or "Convex Hull" option in the "Features" tab of the "Build" floater.

### Reproduction steps

1. Download and install the [Second Life Release 7.1.11.10947335521](https://github.com/secondlife/viewer/releases/tag/Second_Life_Release%23b589d39-ExtraFPS) build.
2. Log in.
3. Open the "Build" floater.
4. Create a box.
5. In the "Build" floater go to the "Features" tab.
6. Change the "Physics Shape Type" parameter to "Prim".
7. Change the "Physics Shape Type" parameter to "Convex Hull" (observe that "Physics Shape Type" is changed to "None").
8. Change the "Physics Shape Type" parameter to "Prim" (observe that "Physics Shape Type" is changed to "None").

**Actual result:**
The "Physics Shape Type" parameter is changed back to the "None" option after choosing the "Prim" or "Convex Hull" option in the "Features" tab of the "Build" floater.

**Expected result:**
The "Physics Shape Type" parameter should be saved in the "Features" tab of the "Build" floater.

**Note:**
This issue is reproduced on Win10/OSX.

This issue was found during ad-hoc testing of [secondlife/viewer/issues/1016](https://github.com/secondlife/viewer/issues/1016) (see "actual_1016.mp4").

**Also**, the "Physics Shape Type" parameter is applied on an object as expected.

This issue is **not reproduced** on the current production build Second Life Release 7.1.10.10800445603.

**actual.mp4**
https://github.com/user-attachments/assets/f819e7cc-23cf-44d9-a5b2-f218f5ec5167
**actual_1016.mp4**
https://github.com/user-attachments/assets/1a4f2e78-ffa5-4209-8b13-78d6212cf8e4

**Comment by AtlasLinden** [comment] 2024-09-25 18:48
For testing, along with the repro steps given above, please test all combo boxes / dropdowns and scroll bars found in each of the following floaters:

- Gestures
- Build
- Inventory 
- Whatever other floaters you may think of! 😸

**Comment by DmitrySProductengine** [comment] 2024-09-30 13:54
Passed QA.
Verified on the Second Life Release 7.1.11.11074622243 (64bit) on Win11/OSX in the scope of [IQA #356](https://github.com/secondlife/iqa/issues/356).
The original bug is not reproduced.

Additional testing of other floaters revealed a couple of known issues:
1. Build floater - Object tab - change shape
https://github.com/secondlife/jira-archive-internal/issues/62609
https://github.com/secondlife/jira-archive-internal/issues/67351

2. Gestures floater
https://github.com/secondlife/jira-archive-internal/issues/161712
This issue is also reproduced for ‘Sound to play’ dropdown.

If the first behavior was discussed and a decision was made not to fix it, then the second behavior is closed (possibly when moving from Jira to GitHub).
@AtlasLinden, could you please pay attention to this behavior and possibly reopen this ticket, if necessary?

No other unexpected behaviors have been detected yet.

**Comment by AtlasLinden** [comment] 2024-10-01 14:35
@DmitrySProductengine thanks for the update!
Yes the first issue does indeed appear to be set as a "won't fix" according to the comments so that will remain so.
As for the second, this was originally closed as "cannot reproduce". Both of us have now reproduced this so I've made a new issue for it here:  https://github.com/secondlife/viewer/issues/2753

**Comment by dmytrohproductengine** [comment] 2024-10-18 07:59
Passed QA.

Verified on the Second Life Release 7.1.11.11296522354 (64bit) on Win10/OSX in the scope of [IQA#366](https://github.com/secondlife/iqa/issues/366).

**Also**, during the testing of the animation gestures floater, the gestures "Animation to play" drop-down box always displays "--None--" (see [secondlife/viewer/issues/2753](https://github.com/secondlife/viewer/issues/2753)).

**Closed** 2024-12-18 19:47 UTC
Labels: bug, team:viewer
