### ISSUE TITLE
[PBR Reflections] Reflection of internal stairs in Linden Homes Houseboat has flattened steps

### ISSUE THREAD

**Issue by aiaustin** [secondlife/viewer#1765] opened 2024-06-14 10:02 UTC
### Environment

Second Life Release 7.1.8.9375512768 (64bit)
Release Notes

You are at 70.0, 14.1, 22.0 in Damiano located at simhost-0299a33f00a321986.agni
SLURL: http://maps.secondlife.com/secondlife/Damiano/70/14/22
(global coordinates 262,214.0, 249,102.0, 22.0)
Second Life Server 2024-04-13.8669470296
Release Notes

CPU: Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (3491.91 MHz)
Memory: 32689 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4529)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.5599
OpenGL Version: 4.6.0 NVIDIA 555.99

Window size: 1240x900
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 256m
Bandwidth: 3000kbit/s
LOD factor: 2
Render quality: 6
Texture memory: 7291MB
Disk cache: Max size 1638.4 MB (87.9% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: FMOD Studio 2.02.20
Dullahan: 1.14.0.202310131404
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.16
Voice Server Version: Not Connected
Packets Lost: 0/25,305 (0.0%)
June 14 2024 02:53:35

### Description

In a Linden Homes houseboat with a Mirror(Everything) mirror probe on a wall mirror, the internal steps inside the houseboat show as a ghost flattened image on top of the stairs top platform. Expectation is that mirror image reflects what is really there in  the houseboat interior.

Note that if the Mirror(Everything) probe is removed and the reflective surface picks up a normal box reflection probe for the internal volume then a clearer wrong flattened image of the stairs appears in that reflection. See attached image "Normal RP on Houseboat shows flat steps.jpg".

![Mirror Everything positioning near houseboat steps](https://github.com/secondlife/viewer/assets/4630885/e0c887a5-cc39-41b0-b661-89f79c503691)
![Mirror Everything probe setup](https://github.com/secondlife/viewer/assets/4630885/2fdab1c6-a67e-4077-949f-75c6326f9bfa)
![Mirror Everything on Houseboat shows flat ghost steps](https://github.com/secondlife/viewer/assets/4630885/7cb1f79c-e61f-4a4d-babb-c3957febab95)
![Normal RP on Houseboat shows flat steps](https://github.com/secondlife/viewer/assets/4630885/a3945637-f3a5-4e23-90de-c0de88b1e377)

### Reproduction steps

1. Go to a Linden Homes houseboat and go inside.
2. Observe the 3 steps internally that lead to the lower level
3. Set up a reflective surface on the wall where the steps will reflect.
4. Set up a box reflective probe (NOT a mirror probe) for the internal space of the houseboat.
5. Observe the reflection of the steps in the reflective surface. Note they are a flat image.
6. Add a Morror (Everything) probe to the reflective surface.
7. Observe that the reflection has changed but from some angles a ghostly image of flattened steps shows on the top surface of the steps area.

**Comment by kylelinden** [comment] 2024-08-06 23:10
Closing as cannot reproduce, feedback from LDPW was that they could not replicate the problem and all the mirror reflections appeared correctly.

**Closed by kylelinden** 2024-08-06 23:10 UTC
Labels: bug, triage
