### ISSUE TITLE
Mirror reflection probes act as static reflection probes until restart

### ISSUE THREAD

**Issue by 7e21** [secondlife/viewer#1243] opened 2024-04-16 06:57 UTC
### Environment

Second Life Release 7.1.6.8666822239 (64bit)
Release Notes

You are at 128.9, 124.4, 23.0 in Rumpus Room 2051 located at simhost-01129fe6e38889eb3.aditi
SLURL: secondlife://Aditi/secondlife/Rumpus%20Room%202051/129/124/23
(global coordinates 36,736.9, 14,460.4, 23.0)
PMFP 2024-04-13.8669470587
Release Notes

CPU: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz (3504 MHz)
Memory: 16333 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.4170)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 2070/PCIe/SSE2

Windows Graphics Driver Version: 31.0.15.5212
OpenGL Version: 4.6.0 NVIDIA 552.12

### Description

When creating a new mirror reflection probe it acts identical to a static reflection probe. (The only visible change when switching from static or dynamic to mirror in the build menu is the "Ambiance" and "Near Clip" input fields being disabled.)

After restarting the viewer the same reflection probe will correctly act as a mirror.
![before_restart](https://github.com/secondlife/viewer/assets/55711895/8184ed16-a83a-466e-a3ed-d8620f844ef2)
![after_restart](https://github.com/secondlife/viewer/assets/55711895/268839b4-4921-44a3-969b-49374627656f)

### Reproduction steps

1: Create a new prim
2: Add a blank PBR material with roughness factor of 0 to the new prim
2: Create a new reflection probe intersecting the prim
3: Change "Probe Update" of the new probe to "Mirror" in the build menu 
(4: Restart)

**Comment by Dan-Linden** [comment] 2024-04-16 21:49
This seems to be a duplicate of https://github.com/secondlife/viewer-private/issues/128

**Closed** 2024-04-16 21:52 UTC
Labels: bug, triage
