### ISSUE TITLE
Alpha mode on blinn-phong materials getting permanently corrupted on occasion

### ISSUE THREAD

**Issue by RunitaiLinden** [secondlife/viewer#1641] opened 2024-06-05 17:30 UTC
### Description

A book has been written about this issue: https://github.com/secondlife/jira-archive-internal/issues/156809

TL;DR -- if the Blinn-Phong diffuse map reports isMissingAsset(), the viewer will set alpha mode to none, and if current viewer has mod permissions on the item in question, it will _actually modify the object so alpha mode will always be none_.

**Comment by akleshchev** [comment] 2024-06-05 19:14
A simple way of causing a missing asset: assign a local texture and an alpha mode then relog. After relog that texture will be missing.

**Comment by akleshchev** [comment] 2024-06-06 12:30
For now marking as Needs more info since I can't repro and davep asked whirly for more info, but added a commit that shows more accurate value in case of a missing asset (keeps the field disabled)

**Comment by Dan-Linden** [comment] 2024-07-08 16:22
What info do we need from Whirly? A recipe to reproduce this bug?

**Comment by akleshchev** [comment] 2024-07-08 16:31
Idealy a scenario, otherwise circumstances and any other data whirly is willing to provide.

**Comment by akleshchev** [comment] 2024-07-10 07:30
Moved linked commit into its own issue as https://github.com/secondlife/viewer/issues/1962, hopefully it will help.

**Comment by Dan-Linden** [comment] 2024-07-16 18:51
Whirly says she does not have a repro for this issue. It's just random.

**Comment by Dan-Linden** [comment] 2024-09-05 19:08
Temporarily opened this so I could link a canny issue, and closed again.

**Closed by Dan-Linden** 2024-09-05 19:08 UTC
Labels: bug, question, maint-pe, needs-test-plan
